# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20180602_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='About_us',
        ),
    ]
