# Generated by Django 2.0.5 on 2018-06-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='other_images1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='other_images2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='other_images3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
