# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20180603_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='other_images1',
            new_name='otherimages1',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='other_images2',
            new_name='otherimages2',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='other_images3',
            new_name='otherimages3',
        ),
    ]
