# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20180603_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Contact',
        ),
    ]
