# Generated by Django 2.0.5 on 2018-06-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20180608_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='intro',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='calorie',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdetail',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
