# Generated by Django 2.0.5 on 2018-06-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20180609_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
