# Generated by Django 2.0.5 on 2018-06-09 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20180609_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
