# Generated by Django 2.0.5 on 2018-06-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20180609_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='calorie',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='weight',
            field=models.TextField(),
        ),
    ]
